### ISSUE TITLE
HS105 not working

### ISSUE THREAD

**Issue by dwmilli** [DaveGut/Hub-Based_TP-Link-to-SmartThings-Integration#3]
This may be my problem, but I can't find it.

Using simulator, clicking the switch icon turns light on but clicking again doesn't turn it off.  It goes back to waiting state.

If I use the on/off buttons in the simulator, then on and off work fine.

Same issue from IOS SmartThing app;  ON works but OFF doesn't.

**Comment by DaveGut** [comment]
1.  The device handler is not designed to support a simulator.
2.  Just completed a test on two actual HS105 using current posted versions.  Running node version 8.1.2.  All worked OK and logs did not have errors.  Test On, Off, Refresh.  One log below.
3.  If you see the error on a real device, please provide the error log entries for the explicit error and maybe I can test.

Thu 01/18/2018
12:21 PM
v8.1.2
Node.js Version Detected:   v8.1.2
TP-Link Hub Console Log


Thu Jan 18 2018 12:22:04 GMT-0600 (Central Standard Time)
IP: 192.168.0.104 sent command deviceCommand
deviceCommand sending to IP: 192.168.0.104 Command: {"system":{"set_relay_state":{"state": 1}}}
Command Response sent to SmartThings


Thu Jan 18 2018 12:22:05 GMT-0600 (Central Standard Time)
IP: 192.168.0.104 sent command deviceCommand
deviceCommand sending to IP: 192.168.0.104 Command: {"system":{"get_sysinfo":{}}}
Command Response sent to SmartThings


Thu Jan 18 2018 12:22:11 GMT-0600 (Central Standard Time)
IP: 192.168.0.104 sent command deviceCommand
deviceCommand sending to IP: 192.168.0.104 Command: {"system":{"set_relay_state":{"state": 0}}}
Command Response sent to SmartThings


Thu Jan 18 2018 12:22:11 GMT-0600 (Central Standard Time)
IP: 192.168.0.104 sent command deviceCommand
deviceCommand sending to IP: 192.168.0.104 Command: {"system":{"get_sysinfo":{}}}
Command Response sent to SmartThings


Thu Jan 18 2018 12:22:14 GMT-0600 (Central Standard Time)
IP: 192.168.0.104 sent command deviceCommand
deviceCommand sending to IP: 192.168.0.104 Command: {"system":{"get_sysinfo":{}}}
Command Response sent to SmartThings
