### ISSUE TITLE
Emeter Error

### ISSUE THREAD

**Issue by cmdrbored** [DaveGut/Hub-Based_TP-Link-to-SmartThings-Integration#5]
Hi,

  When I try to publish the Emeter device handler it keeps giving me the following error:

startup failed:
script_dth_54fa9290_1e24_40c5_ac95_f7083aeed6ff_ver_0_2: 443: unexpected char: 0xA9 @ line 443, column 1.
© 2018 GitHub, Inc.
^

1 error

**Comment by DaveGut** [comment]
The "2018 GitHub, Inc." is not part of the device handler.  It is a part of the base page display outside the code window.

Please try recopying and updating the device handler.  (Note:  I just updated the handlers to accommodate an error that would have occurred on March 1 and 2 of this year, so I recommend using the latest version).

Good luck, and please report back.

**Comment by DaveGut** [comment]
Closed due to no response to mitigation.

**Comment by DaveGut** [comment]
Closed.  No response to mitigation.
